### ISSUE TITLE
How to collect dataset in JASPAR?

### ISSUE THREAD

**Issue by QinglinZhai** [Fanghuachen/AEDNet#2]
Hello, I noticed that you have collected 6 ChIP-seq datasets from the JASPAR database and they are labeled with detailed transcription factor binding sites. As I am new to this research, I would really like to know how you obtained the precise DNA sequence datasets related to the transcription factor binding sites, and whether there is any relevant code for me to refer to? 
Good luck and thanks!

**Comment by Fanghuachen** [comment]
> Hello, I noticed that you have collected 6 ChIP-seq datasets from the JASPAR database and they are labeled with detailed transcription factor binding sites. As I am new to this research, I would really like to know how you obtained the precise DNA sequence datasets related to the transcription factor binding sites, and whether there is any relevant code for me to refer to? Good luck and thanks!

I think you reply to the wrong repository. The question you mentioned seems not related to our work.
