### ISSUE TITLE
The SNR results of the final test were all 0

### ISSUE THREAD

**Issue by wzz-z** [Fanghuachen/AEDNet#4]
When running test_net.py, whether using MAH00444_50.npy, MAH00444_100.npy or my own dataset, the final validation results in only EVENTS, with a number labeled NOISE of 0, resulting in a SNR of 0

**Comment by Fanghuachen** [comment]
Are the training process correct?
















At 2024-09-18 10:40:02, "wzz-z" ***@***.***> wrote:

When running test_net.py, whether using MAH00444_50.npy, MAH00444_100.npy or my own dataset, the final validation results in only EVENTS, with a number labeled NOISE of 0, resulting in a SNR of 0

**Comment by wzz-z** [comment]
Thank you for your guidance, I have solved the above problem, but I have encountered a new problem, when I train my own data (20G) with a device configured with i9-9940X CPU, 125G RAM, 3080Ti GPU, the program only runs when “num-worker=0” , in other cases, the following error occurs:

RuntimeError: DataLoader Worker (pid 29411) killed by signal: killed
